package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_1306601344399438715(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed7755L, 0x1221fb0003efbb5dL, "initial_state")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344398722473(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed76e4L, 0x1221fb0003ed7751L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344398730392(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed76e4L, 0x1221fb0003ed7751L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399012467(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efb643L, 0x1221fb0003efbaf1L, "actuator")), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed76e4L, 0x1221fb0003ed7751L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399075977(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efb643L, 0x1221fb0003efbb61L, "status"), null) ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399130462(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efbaf3L, 0x1221fb0003efbb0fL, "sensor")), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed76e4L, 0x1221fb0003ed7751L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399155485(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efbaf3L, 0x1221fb0003efbb11L, "status"), null) ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399172998(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efbaf3L, 0x1221fb0003efbb13L, "state")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399232554(final PropertyMacroContext _context) {
    return "" + _context.getSessionObject("current_state_name");
  }
  public static Object propertyMacro_GetPropertyValue_1306601344399525321(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static SNode sourceNodeQuery_1306601344399484756(final SourceSubstituteMacroNodeContext _context) {
    _context.putSessionObject("current_state_name", SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efb625L, 0x1221fb0003efbb18L, "transition"));
  }
  public static Iterable<SNode> sourceNodesQuery_1306601344398751446(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed7755L, 0x1221fb0003ed7756L, "bricks"));
  }
  public static Iterable<SNode> sourceNodesQuery_1306601344399461255(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003ed7755L, 0x1221fb0003efbb5aL, "states"));
  }
  public static Iterable<SNode> sourceNodesQuery_1306601344399464038(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x2175b360a87e4c84L, 0x9435b7be1fcf7023L, 0x1221fb0003efb625L, 0x1221fb0003efbb16L, "actions"));
  }
}
