package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum STATUS {
  HIGH("HIGH", true),
  LOW("LOW", false);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final boolean myValue;
  STATUS(String name, boolean value) {
    myName = name;
    myValue = value;
  }
  public boolean getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Boolean.toString(myValue);
  }
  public static List<STATUS> getConstants() {
    List<STATUS> list = ListSequence.fromList(new LinkedList<STATUS>());
    ListSequence.fromList(list).addElement(STATUS.HIGH);
    ListSequence.fromList(list).addElement(STATUS.LOW);
    return list;
  }
  public static STATUS getDefault() {
    return null;
  }
  public static STATUS parseValue(String value) {
    if (value == null) {
      return STATUS.getDefault();
    }
    if (value.equals(STATUS.HIGH.getValueAsString())) {
      return STATUS.HIGH;
    }
    if (value.equals(STATUS.LOW.getValueAsString())) {
      return STATUS.LOW;
    }
    return STATUS.getDefault();
  }
}
